# Generated by Django 4.0.2 on 2022-02-13 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_uservideo_usercourse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uservideo',
            options={'verbose_name': '用户学习视频'},
        ),
    ]
