# Generated by Django 4.0.2 on 2022-02-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_uservideo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.FileField(upload_to='video/%Y%m', verbose_name='视频地址'),
        ),
    ]
