# Generated by Django 4.0.2 on 2022-04-17 23:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_alter_course_add_time_alter_course_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 17, 23, 49, 11, 989768), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 17, 23, 49, 11, 993763), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 17, 23, 49, 11, 990764), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='eights',
            field=models.CharField(db_column='eights', default='空', max_length=50, null=True, verbose_name='第八节'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='fives',
            field=models.CharField(db_column='fives', default='空', max_length=50, null=True, verbose_name='第五节'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='fours',
            field=models.CharField(db_column='fours', default='空', max_length=50, null=True, verbose_name='第四节'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='nines',
            field=models.CharField(db_column='nines', default='空', max_length=50, null=True, verbose_name='第九节'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='ones',
            field=models.CharField(db_column='ones', default='空', max_length=50, null=True, verbose_name='第一节'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sevens',
            field=models.CharField(db_column='sevens', default='空', max_length=50, null=True, verbose_name='第七节'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sixs',
            field=models.CharField(db_column='sixs', default='空', max_length=50, null=True, verbose_name='第六节'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='threes',
            field=models.CharField(db_column='threes', default='空', max_length=50, null=True, verbose_name='第三节'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='twos',
            field=models.CharField(db_column='twos', default='空', max_length=50, null=True, verbose_name='第二节'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 17, 23, 49, 11, 994765), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='video',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 17, 23, 49, 11, 991763), verbose_name='添加时间'),
        ),
    ]
