# Generated by Django 4.0.2 on 2022-05-18 22:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0038_remove_course_is_banner_course_is_publish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 22, 36, 43, 86487), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 22, 36, 43, 90490), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='isVideo',
            field=models.BooleanField(db_column='isvideo', default=False, verbose_name='是否为视频'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 22, 36, 43, 87488), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 22, 36, 43, 91489), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='video',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 22, 36, 43, 88486), verbose_name='添加时间'),
        ),
    ]
