# Generated by Django 4.0.2 on 2022-05-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='image/2022/05/TX8620_12.jpg', upload_to='image/%Y/%m', verbose_name='头像'),
        ),
    ]
