# Generated by Django 4.0.2 on 2022-02-13 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCourse',
        ),
    ]
