# Generated by Django 4.0.2 on 2022-03-20 13:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_course_add_time_alter_courseresource_add_time_and_more'),
        ('users', '0002_alter_userprofile_table'),
        ('operation', '0003_alter_coursecomment_add_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecomment',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 20, 21, 11, 50, 251190), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='userfavorite',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 20, 21, 11, 50, 253191), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 20, 21, 11, 50, 254193), verbose_name='添加时间'),
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2022, 3, 20, 21, 11, 50, 255193), verbose_name='添加时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='课程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile', verbose_name='发布用户')),
            ],
            options={
                'verbose_name': '课程公告',
                'verbose_name_plural': '课程公告',
                'db_table': 'notice',
            },
        ),
    ]
