# Generated by Django 4.0.2 on 2022-05-06 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0022_alter_chatuserlist_options_chatuserlist_touser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuserlist',
            name='touser',
            field=models.IntegerField(default=0, verbose_name='聊天用户'),
        ),
        migrations.AlterField(
            model_name='coursecomment',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 6, 21, 6, 26, 666950), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 6, 21, 6, 26, 669949), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='userfavorite',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 6, 21, 6, 26, 667950), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 6, 21, 6, 26, 668950), verbose_name='添加时间'),
        ),
    ]
