# Generated by Django 4.0.2 on 2022-02-13 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0005_alter_uservideo_options'),
        ('users', '0002_alter_userprofile_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('grade', models.FloatField(verbose_name='成绩')),
                ('rtime', models.DateTimeField(blank=True, null=True, verbose_name='考试时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='考试科目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile', verbose_name='学号')),
            ],
            options={
                'verbose_name': '学生成绩',
                'verbose_name_plural': '学生成绩',
                'db_table': 'record',
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('title', models.TextField(verbose_name='题目')),
                ('qtype', models.CharField(choices=[('单选', '单选'), ('多选', '多选'), ('判断', '判断')], max_length=40, verbose_name='题目类型')),
                ('a', models.CharField(max_length=40, verbose_name='A选项')),
                ('b', models.CharField(max_length=40, verbose_name='B选项')),
                ('c', models.CharField(max_length=40, verbose_name='C选项')),
                ('d', models.CharField(max_length=40, verbose_name='D选项')),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=4, verbose_name='答案')),
                ('difficulty', models.CharField(choices=[('easy', '简单'), ('middle', '中等'), ('difficult', '难')], max_length=10, verbose_name='难度')),
                ('score', models.IntegerField(verbose_name='分值')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='科目')),
            ],
            options={
                'verbose_name': '题库',
                'verbose_name_plural': '题库',
                'db_table': 'questionbank',
            },
        ),
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('title', models.CharField(max_length=40, unique=True, verbose_name='题目')),
                ('time', models.IntegerField(help_text='单位是分钟', verbose_name='考试时长')),
                ('examtime', models.DateTimeField(verbose_name='上次考试时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='科目')),
                ('pid', models.ManyToManyField(to='exam.QuestionBank')),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
                'db_table': 'exampaper',
            },
        ),
    ]
