# Generated by Django 4.0.2 on 2022-04-05 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='exampaper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam.exampaper', verbose_name='试卷'),
            preserve_default=False,
        ),
    ]
